version: "3.9"
services:
    db:
        container_name: postgis
        image: postgis/postgis:latest
        restart: on-failure
        volumes:
            - /usr/local/var/postgres:/var/lib/postgres/data/pgdata
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        networks:
            - main
        expose:
            - 5432
    web:
        container_name: backend_container
        build: .
        command: sh -c "python manage.py collectstatic --no-input && python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
        restart: on-failure
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on:
            - db
        networks:
            - main
        stdin_open: true
        tty: true

networks:
  main:
