# Generated by Django 4.0 on 2021-12-20 03:00

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegram_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, default='POINT(0.0 0.0)', geography=True, null=True, srid=4326),
        ),
    ]
